# Generated by Django 5.1.2 on 2025-01-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ksiazka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_gatunku', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ksiazka',
            options={'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='gatunek',
            field=models.ManyToManyField(to='myapp.gatunek'),
        ),
    ]
