# Generated by Django 5.1.2 on 2025-01-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gatunek_alter_ksiazka_options_ksiazka_gatunek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatunek',
            options={'verbose_name': 'Gatunek', 'verbose_name_plural': 'Gatunki'},
        ),
    ]
