# Generated by Django 5.1.1 on 2025-01-20 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_gatunek_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaWypozyczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField()),
                ('data_zwrotu', models.DateField(default=django.utils.timezone.now)),
                ('ksiazka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_wypozyczen', to='myapp.ksiazka', verbose_name='Książka')),
                ('uzytkownik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_wypozyczen', to='myapp.uzytkownik', verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField(default=django.utils.timezone.now, verbose_name='Data wypożyczenia')),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wypozyczenia', to='myapp.ksiazka')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wypozyczenia', to='myapp.uzytkownik')),
            ],
        ),
    ]
