# Generated by Django 5.1.1 on 2025-01-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_historiawypozyczen_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_autora', models.CharField(max_length=100)),
                ('nazwisko_autora', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ksiazka',
            name='autor',
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='autor',
            field=models.ManyToManyField(to='myapp.autor'),
        ),
    ]
