# Generated by Django 5.1.2 on 2025-01-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_uzytkownik_managers_uzytkownik_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='uzytkownik',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
