# Generated by Django 5.1.2 on 2025-01-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_uzytkownik_managers_alter_uzytkownik_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='wydawnictwo',
            field=models.IntegerField(choices=[(1, 'Inneagencja Dramatu I Teatru'), (2, 'Agencja Wydawnicza Runa'), (3, 'Agencja Wydawniczo Reklamowa Skarpa Warszawska'), (4, 'Alkazar'), (5, 'Alma Press'), (6, 'Ameet'), (7, 'Franciszkańskie Wydawnictwo Św Antoniego'), (8, 'Artrage'), (9, 'Bellona'), (10, 'Biały Kruk'), (11, 'Biuro Literackie'), (12, 'Bogucki Wydawnictwo Naukowe'), (13, 'Cia Books'), (14, 'Convivo'), (15, 'Czuły Barbarzyńca Press'), (16, 'Dom Literatury W Łodzi'), (17, 'Dom Wydawniczy Elipsa'), (18, 'Dom Wydawniczy Rebis'), (19, 'Doświadczalna Oficyna Graficzna'), (20, 'Drzewo Babel'), (21, 'Edycja Świętego Pawła'), (22, 'Elamed Media Group'), (23, 'Elay'), (24, 'Eneteia Wydawnictwo Szkolenia'), (25, 'Escapemagazine Pl'), (26, 'Fabryka Słów'), (27, 'Flos Carmeli'), (28, 'Fundacja Duży Format'), (29, 'Fundacja Festina Lente'), (30, 'Fundacja Instytut Wydawniczy Książka I Presa'), (31, 'Gdańskie Wydawnictwo Psychologiczne'), (32, 'Gebethner I Wolff'), (33, 'Genius Creations'), (34, 'Hejnał'), (35, 'Homo Dei'), (36, 'Towarzystwo Wydawnicze Ignis'), (37, 'Inforteditions'), (38, 'Insignis Media'), (39, 'Instytut Im Oskara Kolberga'), (40, 'Instytut Wydawniczy Pax'), (41, 'Instytut Wydawniczy Latarnik'), (42, 'Isa'), (43, 'Wydawnictwo Kle'), (44, 'Klub Dla Ciebie'), (45, 'Kolegium Europy Wschodniej Im Jana Nowaka Jeziorańskiego'), (46, 'Krakowska Spółka Wydawnicza'), (47, 'Książka I Wiedza'), (48, 'Książnica Atlas'), (49, 'Księgarnia Akademicka'), (50, 'Księży Młyn Dom Wydawniczy'), (51, 'Kurhaus Publishing'), (52, 'Wydawnictwo Kusiński'), (53, 'Lampa I Iskra Boża'), (54, 'Wydawnictwo Literackie'), (55, 'Wydawnictwo Literatura'), (56, 'Ludowa Spółdzielnia Wydawnicza'), (57, 'Ładne Halo'), (58, 'Mamiko'), (59, 'Marpress'), (60, 'Media Rodzina'), (61, 'Młodzieżowa Agencja Wydawnicza'), (62, 'Muza'), (63, 'Mystic Production'), (64, 'Neriton'), (65, 'Wydawnictwo Nisza'), (66, 'Noir Sur Blanc'), (67, 'Norbertinum'), (68, 'Wydawnictwo Novae Res'), (69, 'Nowy Świat'), (70, 'Wydawnictwo Officyna'), (71, 'Oficyna 21'), (72, 'Okultura'), (73, 'Państwowy Instytut Wydawniczy'), (74, 'Phantom Press'), (75, 'Polskie Książki Telefoniczne'), (76, 'Polskie Przedsiębiorstwo Wydawnictw Kartograficznych'), (77, 'Polskie Wydawnictwo Ekonomiczne'), (78, 'Powszechne Wydawnictwo Rolnicze I Leśne'), (79, 'Presscom'), (80, 'Prodoks'), (81, 'Prószyński I Ska'), (82, 'Rosikon Press'), (83, 'Towarzystwo Wydawnicze Rój'), (84, 'Wydawnictwo Salwator'), (85, 'Słowo Prawdy'), (86, 'Słowo Obraz Terytoria'), (87, 'Smak Słowa'), (88, 'Społeczny Instytut Wydawniczy Znak'), (89, 'Spółdzielnia Wydawnicza Czytelnik'), (90, 'Spółdzielnia Wydawnicza Książka'), (91, 'Wydawnictwo Stalker Books'), (92, 'Stowarzyszenie Salon Literacki'), (93, 'Świat Książki'), (94, 'Tern Book'), (95, 'Towarzystwo Autorów I Wydawców Prac Naukowych Universitas'), (96, 'W Drodze'), (97, 'Warbook'), (98, 'Wiedza I Praktyka'), (99, 'Wydawnictwo Wolno'), (100, 'Wolters Kluwer Polska')]),
        ),
    ]
